endpoint: http://localhost:8888
privateKey: 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3 
accountName: buckyjohnson
transaction: esr:gmNgYmBY1mTC_MoglIGBIVzX5uxZRkYGCGCC0qoQynhCw3qviy-DV3vCFLCE-PgHg-iS1OISoCAA
